"""add theme preference to user profiles

Revision ID: a9d1035b387a
Revises: bb72ff9e2950
Create Date: 2026-07-10 17:06:51.620970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d1035b387a'
down_revision: Union[str, None] = 'bb72ff9e2950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('theme_preference', sa.String(), server_default='dark', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'theme_preference')
    # ### end Alembic commands ###
