"""add exercises_master table

Revision ID: bb72ff9e2950
Revises: a3c9d2e4f1b7
Create Date: 2026-07-10 13:15:52.652207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb72ff9e2950'
down_revision: Union[str, None] = 'a3c9d2e4f1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name_en', sa.String(), nullable=False),
    sa.Column('canonical_name_he', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('muscle_group_primary', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name_en')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises_master')
    # ### end Alembic commands ###
